# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 林深时见鹿
subtitle: '晓看天色暮看云，行也思君，坐也思君。春观百花冬观雪，醒亦念卿，梦亦念卿。'
description: '所谓博客，不过是孤芳自赏！'
keywords:
author: 林深时见鹿
# 网站图标
favicon: https://cdn.jsdelivr.net/gh/WPF0414/cdn-Material-X@1.1/favicon/favicon.png
# 作者头像，会出现在文章标题下方，不同于侧边栏的大头像
avatar: https://cdn.jsdelivr.net/gh/WPF0414/cdn-Material-X@1.4.2/avatar/avatar2.jpg
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.ymxcyn.cn
root: /
permalink: post/:abbrlink/
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
 #permalink_defaults:
 #pretty_urls:
 #  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD HH:mm:ss
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: true

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: material-x

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    github: git@github.com:WPF0414/WPF0414.github.io.git
    coding: git@e.coding.net:wpf0414/wpf0414.coding.me.git
    aliyun: git@ymxcyn.cn:/hexoBlog/repo/hexoBlog.git
  branch: master
# 备份
backup:
  type: git
  theme: material-x
  message: Back up my ymxcyn.cn blog
  repository:
    github: git@github.com:WPF0414/WPF0414.github.io.git,backup
    coding: git@e.coding.net:wpf0414/wpf0414.coding.me.git,backup
# RSS
feed:
  type: atom
  path: atom.xml
  limit: false
  content: true
  order_by: -date
  icon: icon.png
  autodiscovery: true
# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: false
  # enable: false
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: live2d-widget-model-koharu
    # use: live2d-widget-model-wanko # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: false # 是否在移动设备上显示
    scale: 0.5 # 移动设备上的缩放
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.8
# 侧边栏小部件
widgets:
  - widget: author
    avatar: https://cdn.jsdelivr.net/gh/WPF0414/cdn-Material-X@1.4.2/avatar/avatar2.jpg
    jinrishici: 所谓博客，不过是孤芳自赏！
    social: true

livere_uid: live2d-widget-model-koharu

# >> 主题配置 ---------------------------------------------------------------------

# 全局导入
import:
  meta:
  - "<meta name='theme-color' content='#FFFFFF'>"
  - "<meta name='msapplication-TileColor' content='#1BC3FB'>"
  - "<meta name='msapplication-config' content='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-favicon@19.9.6/browserconfig.xml'>"
  link:
  - "<link rel='shortcut icon' type='image/x-icon' href='https://cdn.jsdelivr.net/gh/WPF0414/cdn-Material-X@1.1/favicon/favicon.png'>"
  - "<link rel='icon' type='image/x-icon' sizes='32x32' href='https://cdn.jsdelivr.net/gh/WPF0414/cdn-Material-X@1.1/favicon/favicon.png'>"
  - "<link rel='apple-touch-icon' type='image/png' sizes='180x180' href='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-favicon@19.9.6/apple-touch-icon.png'>"
  - "<link rel='mask-icon' color='#1BC3FB' href='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-favicon@19.9.6/safari-pinned-tab.svg'>"
  - "<link rel='manifest' href='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-favicon@19.9.6/site.webmanifest'>"
  # script:

# 评论
leancloud:
  app_id: sm5E4krz0QTDInNR8eBqUXSR-gzGzoHsz
  app_key: jeOWE6uIlDTJLR4z3me3E3gm
#hexo sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
